### ISSUE TITLE
Incorrect Behavior of the RGB Sliders

### ISSUE THREAD

**Issue by aldidoanta** [filnow/bg-changer#1]
Hi, thank you for creating this tool!

It looks like the behaviors of the red slider and the blue slider are swapped.

I use the `city.jpg` file as an example.
![Screenshot from 2024-02-27 16-29-49](https://github.com/filnow/bg-changer/assets/4391973/c62ea158-2b91-4999-b2ce-174906e5f6ec)

If I slide the red slider to the right, the output will show a bluish color.
![Screenshot from 2024-02-27 16-30-03](https://github.com/filnow/bg-changer/assets/4391973/f37cf5a6-b5a7-478a-a4f9-23070976a32a)

If I slide the blue slider to the right, the output will show a reddish color.
![Screenshot from 2024-02-27 16-30-19](https://github.com/filnow/bg-changer/assets/4391973/efc63dd3-1932-45df-82aa-276398642081)

**Comment by aldidoanta** [comment]
I'll create a PR to fix this issue.

**Comment by filnow** [comment]
Yes there is a bug, probably because OpenCV is storing a image in BGR format. Looking in ur updated PR right now. Thanks for finding this!
